### ISSUE TITLE
Suggestions working only in files on main directory level

### ISSUE THREAD

**Issue by ukoste** [tststs/atom-ternjs#186]
Hi, 

I have some issues regarding autocomplete. After the update to 0.12.0 tern.js auto complete suggestion stopped working. Autocomplete window appears only on 1 or 2 files that are in the root of the project folder.

I'm using my project folder with combination of Remote-FTP. 

No error msg are shown, simply ctrl-space doesn't do anything.

Regards, ukos

**Comment by sheepcount** [comment]
Same here, updated and stopped working. Downgraded and works again. I do not get any suggestions at all, after disabling ternjs I do at least get the default autocomplete+ suggestions.

* Can confirm that top level folder files still work fine.
* My project is on a local hard drive on Windows 10.
* I didn't have a .tern-project until now, but I now tried creating one, didn't make a difference.
* Files do seem to be indexed if I have the indexed files logged to console.

**Comment by ukoste** [comment]
Hi, how did u downgrade?

**Comment by sheepcount** [comment]
You can use apm to install a specific package version, 0.11.3 is the latest before 0.12.0:
`apm install atom-ternjs@0.11.3`

**Comment by tststs** [comment]
What do you mean by top level directory? Are all files in the same root project folder or does completion doesn't work if the files are outside of this project folder?

Please give me a hint how the structure of the project is and in which files no suggestions are displayed.

Greetings.

**Comment by apetraru** [comment]
I'm having the same issue.
Files in the root work (main.js).
Files inside folders (app/main.js) do not work.
![tern](https://i.imgur.com/UEr7t0J.png?1)

**Comment by tststs** [comment]
Operating system? OSX works as expected, i'll have a look at windows now.

**Comment by apetraru** [comment]
OS is Windows, tested on 7 and 10, issue reproduces on both.

**Comment by tststs** [comment]
Ok, spotted the problem. I published a quick fix. Should be working after the update.
Keeping this ticket since this is only a quick fix.

Greetings.

**Comment by tststs** [comment]
Referenced the wrong issue. 945d14b

**Comment by ukoste** [comment]
I tested the fix on Windows 7, and it works! Thank you. I appreciate the effort you invested.

Regards, ukoste

**Comment by PlanOff** [comment]
Hi everyone,

I'm having the same issue on Windows 10 even after latest update.
Reverting to apm install atom-ternjs@0.11.3 solved the problem, but it means that I can't update anymore, please take a look if it's possible.

Thank you,
Vladimir

**Comment by AliShug** [comment]
Same issue here, Windows 10 on 12.1. The quick-fix only corrects one level deep, I'm still seeing the problem with a more nested folder structure.

So...
`/test.js` Works
`/js/test.js` Works
`/src/js/test.js` Broken

Downgraded to 0.11.3 for now.

**Comment by AliShug** [comment]
Sweet 0.12.2 fixes it for me! Thanks for the ridiculously quick response :100:
